@startuml

skinparam participant {
    FontColor black
    BorderColor black
}

skinparam participant {
    BackgroundColor<<AWS-Cognito>> #4D27A8
    BorderColor<<AWS-Cognito>> #341D78
    FontColor<<AWS-Cognito>> white
}

actor User

participant "Frontend (UI)" as UI
participant "Backend API" as API
database "Database" as DB
participant "User Authentication" as Cognito <<AWS-Cognito>>

User -> UI : Complete confirm password form
UI -> API : Send confirm password request

API -> DB : Get user by username
DB --> API : Response user

API -> Cognito : Confirm password with confirmation code
Cognito --> API : Response successful

API --> UI : Response successful
UI -> User : Show success toast and redirect to sign in page

@enduml
